In [1]:
import pandas as pd
#from google.colab import drive
#drive.mount('/content/gdrive')

In [2]:
import pandas as pd

#Oficina Pré Processamento

#Dataset
###https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset

In [3]:
df=pd.read_csv('/content/Sleep_health_and_lifestyle_dataset.csv')

In [4]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

#Seleção de Variavel
* Excluir Person ID

In [5]:
df = df.drop(columns=['Person ID'])

In [6]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

### Primeiro Vamos Normalizar a Idade
  * Precisamos do valor máximo e mínimo

In [7]:
df['Age'].max()

59

In [8]:
df['Age'].min()

27

In [9]:
def Age_normalizacao(x):
    x=(x-27)/(59-27)
    return x

In [10]:
df['Age_normal'] = df.apply(lambda x: Age_normalizacao(x['Age']), axis=1)

In [11]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Age_normal
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN,0.00000
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,0.03125
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,0.03125
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,0.03125
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,0.03125

### Encoding da Variável Occupation
* Variável Nominal
*Vamos gerar uma coluna nova para cada variável!
*(One hot encoding)

In [12]:
ocupations=list(df['Occupation'].unique())
print(ocupations)

['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher', 'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer', 'Salesperson', 'Manager']

In [13]:
import numpy as np
for profissao in ocupations:
  df[profissao] = np.where(df['Occupation']==profissao, 1, 0)

In [14]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,...,Doctor,Sales Representative,Teacher,Nurse,Engineer,Accountant,Scientist,Lawyer,Salesperson,Manager
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,...,0,0,0,0,0,0,0,0,0,0
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,1,0,0,0,0,0,0,0,0,0
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,1,0,0,0,0,0,0,0,0,0
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,1,0,0,0,0,0,0,0,0
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,1,0,0,0,0,0,0,0,0

###Encoding da Variável BMI Category e Sleep Disorder
* Variável Ordinal
*Atribuir um valor para cada categoria

In [15]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [16]:
BMI_category_list=list(df['BMI Category'].unique())

In [17]:
print(BMI_category_list)

['Overweight', 'Normal', 'Obese', 'Normal Weight']

In [18]:
BMI_category_list.sort(reverse=True)
BMI_category_list
#testar sem reverse

['Overweight', 'Obese', 'Normal Weight', 'Normal']

In [19]:
def BMI_Category_encoding(x):
    encoding=BMI_category_list.index(x)
    #if x=='Overweight'
    #  encoding=10

    return encoding

Sleep_Disorder_encoding_list=list(df['Sleep Disorder'].unique())
def Sleep_Disorder_encoding(x):
    encoding=Sleep_Disorder_encoding_list.index(x)
    return encoding

In [20]:
df['BMI_Category_encoding'] = df.apply(lambda x: BMI_Category_encoding(x['BMI Category']), axis=1)

In [21]:
df['Sleep_Disorder_encoding'] = df.apply(lambda x: Sleep_Disorder_encoding(x['Sleep Disorder']), axis=1)

In [22]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,...,Teacher,Nurse,Engineer,Accountant,Scientist,Lawyer,Salesperson,Manager,BMI_Category_encoding,Sleep_Disorder_encoding
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,...,0,0,0,0,0,0,0,0,0,0
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,0,0,0,0,0,0,3,0
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,0,0,0,0,0,0,3,0
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,0,0,0,0,0,0,1,1
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,0,0,0,0,0,0,1,1

### Encoding da Variável Gender
* Variável Nominal
*Vamos gerar uma coluna nova para cada variável!
*(One hot encoding)

In [23]:
Gender_list=list(df['Gender'].unique())
print(Gender_list)

for gen in Gender_list:
  df[gen] = np.where(df['Gender']==gen, 1, 0)
df.head()

['Male', 'Female']

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,...,Engineer,Accountant,Scientist,Lawyer,Salesperson,Manager,BMI_Category_encoding,Sleep_Disorder_encoding,Male,Female
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,...,0,0,0,0,0,0,0,0,1,0
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,0,0,0,0,3,0,1,0
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,0,0,0,0,3,0,1,0
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,0,0,0,0,1,1,1,0
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,0,0,0,0,1,1,1,0

In [24]:
list(df.columns)

['Gender',
 'Age',
 'Occupation',
 'Sleep Duration',
 'Quality of Sleep',
 'Physical Activity Level',
 'Stress Level',
 'BMI Category',
 'Blood Pressure',
 'Heart Rate',
 'Daily Steps',
 'Sleep Disorder',
 'Age_normal',
 'Software Engineer',
 'Doctor',
 'Sales Representative',
 'Teacher',
 'Nurse',
 'Engineer',
 'Accountant',
 'Scientist',
 'Lawyer',
 'Salesperson',
 'Manager',
 'BMI_Category_encoding',
 'Sleep_Disorder_encoding',
 'Male',
 'Female']

##Normalizacao

*Columns : Sleep Duration ; Physical Activity Level; Heart Rate ;Daily Steps ;

In [25]:


print(df['Sleep Duration'].max())
print(df['Sleep Duration'].min())


print(df['Physical Activity Level'].max())
print(df['Physical Activity Level'].min())


print(df['Heart Rate'].max())
print(df['Heart Rate'].min())


print(df['Daily Steps'].max())
print(df['Daily Steps'].min())

8.5
5.8
90
30
86
65
10000
3000

In [26]:
def Sleep_Duration_normalizacao(x):
    x=(x-5.8)/(8.5-5.8)
    return x
def Physical_Activity_Level_normalizacao(x):
    x=(x-30)/( 90-30)
    return x
def Heart_Rate_normalizacao(x):
    x=(x-65)/(86-65)
    return x
def Daily_Steps_normalizacao(x):
    x=(x-3000)/(10000-3000)
    return x

In [27]:
df['Sleep Duration_normal'] = df.apply(lambda x: Sleep_Duration_normalizacao(x['Sleep Duration']), axis=1)
df['Physical Activity Level_normal'] = df.apply(lambda x: Physical_Activity_Level_normalizacao(x['Physical Activity Level']), axis=1)
df['Heart Rate_normal'] = df.apply(lambda x: Heart_Rate_normalizacao(x['Heart Rate']), axis=1)
df['Daily Steps_normal'] = df.apply(lambda x: Daily_Steps_normalizacao(x['Daily Steps']), axis=1)

In [28]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,...,Salesperson,Manager,BMI_Category_encoding,Sleep_Disorder_encoding,Male,Female,Sleep Duration_normal,Physical Activity Level_normal,Heart Rate_normal,Daily Steps_normal
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,...,0,0,0,0,1,0,0.111111,0.2,0.571429,0.171429
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,3,0,1,0,0.148148,0.5,0.476190,1.000000
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,0,3,0,1,0,0.148148,0.5,0.476190,1.000000
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,1,1,1,0,0.037037,0.0,0.952381,0.000000
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,0,1,1,1,0,0.037037,0.0,0.952381,0.000000

## Validar variavel Blood Pressure
* A variável está invalida pro modelo. Vamos realizar um encoding valido

In [29]:
def fix_variavel(x):
    b1=x.split('/')[0]
    b2=x.split('/')[1]
    bp_encoding=int(b2)/int(b1)
    return bp_encoding

df['Blood Pressure_normal']= df.apply(lambda x: fix_variavel(x['Blood Pressure']), axis=1)

In [30]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,...,Manager,BMI_Category_encoding,Sleep_Disorder_encoding,Male,Female,Sleep Duration_normal,Physical Activity Level_normal,Heart Rate_normal,Daily Steps_normal,Blood Pressure_normal
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,...,0,0,0,1,0,0.111111,0.2,0.571429,0.171429,0.658730
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,3,0,1,0,0.148148,0.5,0.476190,1.000000,0.640000
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,...,0,3,0,1,0,0.148148,0.5,0.476190,1.000000,0.640000
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,1,1,1,0,0.037037,0.0,0.952381,0.000000,0.642857
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,...,0,1,1,1,0,0.037037,0.0,0.952381,0.000000,0.642857

#VAMOS CRIAR UM CLASSIFICADOR
* SVM

1.   Selecionar as Features
2.   Selecionar os Labels

In [31]:
cls=list(df.columns)

In [32]:
cls

['Gender',
 'Age',
 'Occupation',
 'Sleep Duration',
 'Quality of Sleep',
 'Physical Activity Level',
 'Stress Level',
 'BMI Category',
 'Blood Pressure',
 'Heart Rate',
 'Daily Steps',
 'Sleep Disorder',
 'Age_normal',
 'Software Engineer',
 'Doctor',
 'Sales Representative',
 'Teacher',
 'Nurse',
 'Engineer',
 'Accountant',
 'Scientist',
 'Lawyer',
 'Salesperson',
 'Manager',
 'BMI_Category_encoding',
 'Sleep_Disorder_encoding',
 'Male',
 'Female',
 'Sleep Duration_normal',
 'Physical Activity Level_normal',
 'Heart Rate_normal',
 'Daily Steps_normal',
 'Blood Pressure_normal']

In [71]:
features=cls[12:-1]#+cls[4:5]+cls[6:7]######

In [72]:
features.remove('Sleep_Disorder_encoding')

In [73]:
features

['Age_normal',
 'Software Engineer',
 'Doctor',
 'Sales Representative',
 'Teacher',
 'Nurse',
 'Engineer',
 'Accountant',
 'Scientist',
 'Lawyer',
 'Salesperson',
 'Manager',
 'BMI_Category_encoding',
 'Male',
 'Female',
 'Sleep Duration_normal',
 'Physical Activity Level_normal',
 'Heart Rate_normal',
 'Daily Steps_normal']

In [74]:
label=cls[-8]

In [75]:
label

'Sleep_Disorder_encoding'

In [76]:
df_label=df[label]

In [77]:
df_features = df[features]

In [78]:
df_label.head()

0    0
1    0
2    0
3    1
4    1
Name: Sleep_Disorder_encoding, dtype: int64

In [79]:
df_features.head()

,Age_normal,Software Engineer,Doctor,Sales Representative,Teacher,Nurse,Engineer,Accountant,Scientist,Lawyer,Salesperson,Manager,BMI_Category_encoding,Male,Female,Sleep Duration_normal,Physical Activity Level_normal,Heart Rate_normal,Daily Steps_normal
0,0.00000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0.111111,0.2,0.571429,0.171429
1,0.03125,0,1,0,0,0,0,0,0,0,0,0,3,1,0,0.148148,0.5,0.476190,1.000000
2,0.03125,0,1,0,0,0,0,0,0,0,0,0,3,1,0,0.148148,0.5,0.476190,1.000000
3,0.03125,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0.037037,0.0,0.952381,0.000000
4,0.03125,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0.037037,0.0,0.952381,0.000000

# O Modelo espera como entrada para treino np.array

In [80]:
import numpy as np

labels_np = np.array(df_label)


features_np = np.array(df_features)

## Separar em treino e teste

In [81]:

from sklearn.model_selection import train_test_split
# Split the data into training and testing sets

train_features, test_features, train_labels, test_labels = train_test_split(features_np, labels_np, test_size = 0.25, random_state = 42)

In [82]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (280, 19)
Training Labels Shape: (280,)
Testing Features Shape: (94, 19)
Testing Labels Shape: (94,)

Treine o Modelo

In [105]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#  'rbf', 'poly'
#rf = SVC(kernel='poly', random_state=42)
rf = RandomForestClassifier(n_estimators=100, criterion ='gini')#
# Treinar o modelo nos dados de treinamento
rf.fit(train_features, train_labels)

RandomForestClassifier()

# Previsão

In [101]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
predictions

array([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0,
       0, 2, 2, 0, 2, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0])

In [102]:
test_labels

array([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0,
       0, 2, 2, 0, 2, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0])

In [103]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(test_labels, predictions)

0.8936170212765957

In [104]:
confusion_matrix(test_labels,predictions)

array([[54,  0,  1],
       [ 1, 16,  5],
       [ 1,  2, 14]])

#Mão na Massa
* Exclua algumas features e tente um resultado melhor que o meu! 87 %

In [50]:
features

['Age_normal',
 'Software Engineer',
 'Doctor',
 'Sales Representative',
 'Teacher',
 'Nurse',
 'Engineer',
 'Accountant',
 'Scientist',
 'Lawyer',
 'Salesperson',
 'Manager',
 'BMI_Category_encoding',
 'Male',
 'Female',
 'Sleep Duration_normal',
 'Physical Activity Level_normal',
 'Heart Rate_normal',
 'Daily Steps_normal',
 'Quality of Sleep',
 'Stress Level']

### Sugestão
Retire as Variáveis Subjetivas
['Quality of Sleep','Stress Level']

In [51]:

features_2 = features[0:1] + features[12:-6]

In [52]:
features_2

['Age_normal', 'BMI_Category_encoding', 'Male', 'Female']

In [53]:

df_features_2 = df[features_2]